configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/irrigation-solutions-software-development/init_omega.py-2f8a48330e9364042fd96eebf566ffcf706279f1b1c5fcb2a5d5fa3547f556b4.yml
openapi_spec_hash: 356a7298b2abac3fdf72ad5ee046b952
config_hash: d79f79c5f161df784883af517d6e7839
