configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/irrigation-solutions-software-development/init_omega.py-895f18e01f3841eab69f6ddcaae4f21c181269e597e1046cffd6854fcf5c7c44.yml
openapi_spec_hash: 356a7298b2abac3fdf72ad5ee046b952
config_hash: 1426c43eb5c4ff4a50ec412ad588259a
