configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/irrigation-solutions-software-development/init_omega.py-fedf4507da4204d3e4d8c74cc531de087e4c3b7cb8f57104311ad76b5a5d366b.yml
openapi_spec_hash: 356a7298b2abac3fdf72ad5ee046b952
config_hash: 5d510670e1ebf3d04683fdd7312e3450
