#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/stainless-sdks/init_omega.py-go"

echo "==> Building init-omega-py"
go build ./cmd/init-omega-py
